name: driver_hiring_mobile
description: Driver Hiring App - Flutter starter (compact)
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_auth: ^4.6.0
  firebase_database: ^10.0.7
  firebase_storage: ^11.0.9
  firebase_messaging: ^14.6.4
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  http: ^0.14.0
  razorpay_flutter: ^1.3.6

flutter:
  uses-material-design: true
