version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driverdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/driverdb
      - FIREBASE_SERVICE_ACCOUNT_PATH=./serviceAccountKey.json
      - FIREBASE_DATABASE_URL=https://<YOUR_FIREBASE_PROJECT>.firebaseio.com
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
volumes:
  pgdata:
